install:
  - bundle install --path vendor/bundle
  - gem install bundler
  - npm ci

script: npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  repo: initiative-interchange/initiative-interchange.github.io
  local_dir: _site
  on:
    branch: master

